# Generated by Django 3.0.5 on 2020-04-09 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('amazon_url', models.URLField()),
                ('author', models.CharField(max_length=50)),
                ('genre', multiselectfield.db.fields.MultiSelectField(choices=[('fiction', 'Fiction'), ('sci-fi', 'Sci-Fi'), ('thiller', 'Thriller'), ('adventure', 'Adventure'), ('crime', 'Crime')], max_length=38)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('books', models.ManyToManyField(to='app.Book')),
            ],
        ),
    ]
